{% set version = "5.2.0" %}

package:
  name: rise
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rise/rise-{{ version }}.tar.gz
  sha256: 514eb8784b8d4f7c2af4ba77055fd7a7d8365a87e55eb118d2f7a3ea400dbd7b

build:
  number: 4
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - notebook >=5.0.0
  run:
    - python
    - notebook >=5.0.0

test:
  imports:
    - rise

about:
  home: https://github.com/damianavila/RISE
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'RISE: Live Reveal.js Jupyter/IPython Slideshow Extension'
  description:  Reveal.js - Jupyter/IPython Slideshow Extension, also known as live_reveal. Quickly turn your Jupyter Notebooks into a live presentation.  
  doc_url: https://damianavila.github.io/RISE/
  dev_url: https://github.com/damianavila/RISE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
