travis:
  secure:
    BINSTAR_TOKEN: nA2D3M73qrMFofTVR2JNKdkrG3YWnkdWr3kMPyrJCuQ19onEilKyGFe8gMgkjL4Ljv9DJ+87eq8UytjpfdpBtxGT1xuh8yEPPPkOzmvGPvJW8sK2oyvRgHkZat5FpODDEccd31lYdExPFtUe0e/q129uN8fu061PHqKCyxFUyVUXX+ygkXaHdIidY7k5t9xQNDQzk4NihHoBI3HcIDavk5JFQckHbqvRhSQWNFo9nUblLbFzOIzdw+qZaRUEzTL07TupXsNaRw2UX4jke4z9pcjNqrkQVy7nsbbyPwhPZXZHbiG/I0tfoJKCBBjvZUwloaT7KnmVtN+meXB0onwEFb+pv4iMeK3YpUR9+KgV31E/FjurJhm1UCv+lVscdrzgSbD11s+cNV/lnJUPVYrDyrhQlguqtdCO3NJGLTxRqZkp8JxzAUFmRuI6uw7cS4qiUmlLKvVjKCfBOAAWYX1H9UbBj7vWf3NVKsElYUD/xeO7HNBY572l0rEVNJy/ojIsf1xWmlIYBYaCyWD+CP7Fxgla/HgWmd/s1EZpzqfrjpKT5smf4Gq9Qw452fgGzqLkknGBYTMypt2dU03gb6vWHUkuSS1fTmnKBJdwAazcf/h5dbAEvLc62zJejVB+vD0we2TfssYN1IMFc2+3y9hzFeNqe/g+m694XSK+suW/KQI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
