travis:
  secure:
    BINSTAR_TOKEN: RkvICVwh037deFXITctMcjRnCir7hlZemTd0/AtiRARKCxTdFAMQavR11IlMqn18c3V8NrJbNFNqCfiJNAVIgZ4CGPC8x9lfnQH53sd99njSiX7pIVIUsJTgZgEvWeLPv5HcsD6rQbEG0dAitTJWIFkEtQy/IW8QzQIBuBsYzs8n0cnGJjqhADXQdAIUnMSsalT/oM55hNU25M0xLxVakKQcMoIKCFvyteZu4jFYdQfo6I6pnKLzuuY0UCaaPzTdD2fMgFN0cmkHNad9YegIelk8T7QdP5Ti06q/p5Wum5OQMjKTi1nGHao7jEJnWokyLn9MxnViJfquig+46fmP2DNL/BmMil3SLtf+2qDOjJgea3pzRxlj9H+kmiSQDBpv0qQ1jklwRY7QDTqO+kc4Vsj2lhypd+a6eXJI+Z54y75nAWX86y7q8Sl2q9OUDV6BgK3X8CMAnIiQdn8HcUpjYKaZKIruUnQ8zPEJIAI54ZFpP9OBRc/0bgO/sLyUhH26Qb6dQBB0XPXMdSg+ma1ZPSMoapUbR42bX1ZlfUXJcDtjioiBX+IraeG6sKrSSojIVTIUc5GS1DgBhzkXo6CzpqMFSIq5wdbb/+gBBitzXJk3kBlNhSNl6ams1AJvpedEeWkr6CTXnjyet4fXJamYrvE8ruzfMSD4UOScKtHD+uc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
